// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eenvuubwwlckbpdprbex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlbnZ1dWJ3d2xja2JwZHByYmV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5Mzg1MDQsImV4cCI6MjA2ODUxNDUwNH0.eQCJYCIJdCRA-gyrX_F8cwGfR62wP6xhC4mj_8aH4Xg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});